### PR TITLE
[netcdf] GRIB support.

### PR DESCRIPTION
**Pull request by harold**
Upgrading the ucar lib to a newer version that supports GRIB.

Not 100% sure the full ramifications of this, but it does let me open the `hrrr` files.

### CODE REVIEW

**Comment by cnuernber** [comment]
The old netcdfAll library broke libpython bc/ it compiled in an ancient jna.  If this one compiles in a somewhat more recent JNA and works with libpython then we are good.  I would rather find the sub-module required to enable this from the netcdfAll build and include only that one.

**Comment by harold** [comment]
oic, is it easy for you to test to see if this broke it?

CDM seems to be from March 2015: https://mvnrepository.com/artifact/edu.ucar/cdm

netcdfALL is from Feb 2019: https://mvnrepository.com/artifact/edu.ucar/netcdfAll/4.6.13

**Comment by cnuernber** [comment]
Yes, it is very easy.  I just tried a quick pathway to see if including the grib jar would fix things and it did not so I will just leave what you had, install, and see if I can use libpython.

**Comment by cnuernber** [comment]
Yep, this breaks downloading source models:

10:46:31.932 [nRepl-session-800d9fa9-e1bc-4b84-90a0-5df8f252f402] INFO  libpython-clj.python.logging - executing python initialize!
10:46:31.940 [nRepl-session-800d9fa9-e1bc-4b84-90a0-5df8f252f402] INFO  tech.jna.base - Library python3.7m found at [:system "python3.7m"]
10:46:31.961 [tech.resource.gc ref thread] INFO  tech.resource.gc - Reference thread starting
Syntax error (IllegalAccessError) compiling at (fathym_forecast/source_data.clj:24:1).
tried to access class com.sun.jna.CallbackReference from class libpython_clj.python.object$apply_method_def_data_BANG_

**Comment by cnuernber** [comment]
Let me work on this.  You have a test so and I will ensure that both the test passes and we can load libpython :-).

**Comment by harold** [comment]
You the man.

**Comment by cnuernber** [comment]
@harold Version 0.13 is up on clojars

**Pull request merged**
